lang: en_US
title: Strixx
author: Maximous Black
tagline: Open Directory Search Tool
description: Open Directory Search Tool

url: "https://xuac.github.io"
baseurl: "/strixx"

google_site_verification: M4wcsX_DZ9CkpAzZ5rNmUbk1JWl3aLqgxIfB4YG-ozI
google_analytics: UA-131672698-4

footer_url: "https://github.com/xuac/strixx/"
footer_text: "Star on GitHub"

logo: logo.svg
favicon: favicon.ico

sass:
    style: compressed
    sass_dir: css
